"""Readonly inspection and rendering for ``davo im info``."""

import io
import logging
import os
from functools import lru_cache
from typing import Any, Dict, Iterable, Optional, Sequence, Tuple

from PIL import ExifTags, Image

from davo.utils import format as format_utils

logger = logging.getLogger(__name__)


_ORIENTATION_TAG = 274
_DATE_TIME_TAG = 306
_DATE_TIME_ORIGINAL_TAG = 36867
_MAKE_TAG = 271
_MODEL_TAG = 272


@lru_cache(maxsize=1)
def _pillow_jpeg_quantization_tables() -> Dict[
    int, Tuple[Tuple[int, ...], ...]
]:
    """Return the quantization tables Pillow writes at every JPEG quality."""
    tables = {}
    for quality in range(1, 101):
        output = io.BytesIO()
        Image.new("RGB", (8, 8)).save(output, format="JPEG", quality=quality)
        with Image.open(io.BytesIO(output.getvalue())) as image:
            quantization = image.quantization
            tables[quality] = tuple(
                tuple(quantization[index]) for index in sorted(quantization)
            )
    return tables


def estimate_jpeg_quality(image: Image.Image) -> str:
    """Estimate a JPEG's quality from quantization tables, or return ``-``.

    JPEG quality is encoder-specific metadata in practice, so custom tables are
    reported as the closest table set generated by Pillow's standard encoder.
    """
    if image.format != "JPEG":
        return "-"

    try:
        quantization = image.quantization
        if not quantization:
            return "-"
        actual_tables = tuple(
            tuple(quantization[index]) for index in sorted(quantization)
        )
        if len(actual_tables) not in {1, 2} or any(
            len(table) != 64 for table in actual_tables
        ):
            return "-"

        candidates = _pillow_jpeg_quantization_tables()
        best_quality = min(
            candidates,
            key=lambda quality: sum(
                abs(actual - expected)
                for actual_table, expected_table in zip(
                    actual_tables, candidates[quality][:len(actual_tables)]
                )
                for actual, expected in zip(actual_table, expected_table)
            ),
        )
        return str(best_quality)
    except (AttributeError, KeyError, OSError, TypeError, ValueError):
        return "-"


def _format_resolution(dpi: Any) -> str:
    if not isinstance(dpi, (tuple, list)) or len(dpi) < 2:
        return "-"
    try:
        x_dpi, y_dpi = (int(round(float(value))) for value in dpi[:2])
    except (TypeError, ValueError, OverflowError):
        return "-"
    if x_dpi <= 0 or y_dpi <= 0:
        return "-"
    if x_dpi == y_dpi:
        return f"{x_dpi} dpi"
    return f"{x_dpi}x{y_dpi} dpi"


def _orientation_for_size(width: int, height: int) -> str:
    if width == height:
        return "square"
    return "landscape" if width > height else "portrait"


def _safe_exif_value(value: Any) -> str:
    """Keep tag values readable and prevent them from creating output lines."""
    try:
        value = str(value)
    except Exception:  # pragma: no cover - defensive for Pillow extensions
        value = repr(value)
    return value.replace("\\", "\\\\").replace("\r", "\\r").replace(
        "\n", "\\n"
    )


def _exif_tags(exif: Any) -> list[tuple[str, str]]:
    tags = []
    for tag_id, value in exif.items():
        name = ExifTags.TAGS.get(tag_id, f"Tag {tag_id}")
        tags.append((str(name), _safe_exif_value(value)))
    return sorted(tags, key=lambda item: (item[0].casefold(), item[0]))


def inspect_image(input_file: str, verbose: bool = False) -> Optional[dict]:
    """Return metadata for a regular Pillow-readable image, or ``None``."""
    if not os.path.isfile(input_file):
        if verbose:
            logger.warning("im.info: not a regular file: %s", input_file)
        return None

    try:
        with Image.open(input_file) as image:
            exif = image.getexif()
            width, height = image.size
            # Orientations 5--8 transpose the displayed dimensions.
            if exif.get(_ORIENTATION_TAG) in (5, 6, 7, 8):
                width, height = height, width

            make = _safe_exif_value(exif.get(_MAKE_TAG, "-"))
            model = _safe_exif_value(exif.get(_MODEL_TAG, "-"))
            date = exif.get(_DATE_TIME_ORIGINAL_TAG) or exif.get(
                _DATE_TIME_TAG
            )
            return {
                "format": image.format or "-",
                "image_size_px": f"{width}x{height} px",
                "quality": estimate_jpeg_quality(image),
                "resolution": _format_resolution(image.info.get("dpi")),
                "orientation": _orientation_for_size(width, height),
                "mode": image.mode or "-",
                "file_size": format_utils.humanize_bytes(
                    os.path.getsize(input_file)
                ).strip(),
                "exif": "yes" if exif else "no",
                "date": _safe_exif_value(date) if date else "-",
                "camera": f"{make} {model}",
                "exif_tags": _exif_tags(exif),
            }
    except (Image.DecompressionBombError, OSError, ValueError) as exc:
        if verbose:
            logger.warning(
                "im.info: cannot read image %s: %s", input_file, exc
            )
        return None


def format_image_info_report(
    rows: Sequence[dict],
    table: bool = False,
    compact: bool = False,
    include_exif: bool = False,
    image_number_width: Optional[int] = None,
) -> str:
    """Format image rows in the same TSV/ASCII-table style as ``pdf info``."""
    headers = [
        "Format",
        "ImageSizePx",
        "Quality",
        "Resolution",
        "Orientation",
        "Mode",
        "FileSize",
        "EXIF",
    ]
    fields = [
        "format",
        "image_size_px",
        "quality",
        "resolution",
        "orientation",
        "mode",
        "file_size",
        "exif",
    ]
    if include_exif:
        headers.extend(("Date", "Camera"))
        fields.extend(("date", "camera"))

    table_rows = []
    for row in rows:
        values = [str(row[field]) for field in fields]
        if compact:
            width = image_number_width or len(str(row["total_images"]))
            values.insert(
                0,
                f'{row["image"]:0{width}d}/{row["total_images"]:0{width}d}',
            )
        table_rows.append(values)

    if compact:
        headers.insert(0, "Image")
    widths = [0 if compact else len(header) for header in headers]
    for row in table_rows:
        for index, value in enumerate(row):
            widths[index] = max(widths[index], len(value))

    if table:
        border = "+{}+".format("+".join("-" * (width + 2) for width in widths))

        def format_row(row: Iterable[str]) -> str:
            return "| {} |".format(
                " | ".join(
                    value.rjust(widths[index]) if index == 0 else value.ljust(
                        widths[index]
                    )
                    for index, value in enumerate(row)
                )
            )

        if compact:
            return "\n".join(
                (border, *(format_row(row) for row in table_rows), border)
            )
        return "\n".join(
            (
                border,
                format_row(headers),
                border,
                *(format_row(row) for row in table_rows),
                border,
            )
        )

    rendered = []
    if not compact:
        rendered.append(
            "  ".join(
                header.ljust(widths[index])
                for index, header in enumerate(headers)
            )
        )
    for row in table_rows:
        rendered.append(
            "  ".join(
                value.ljust(widths[index]) for index, value in enumerate(row)
            )
        )
    return "\n".join(rendered)


def format_exif_block(row: dict) -> str:
    return "\n".join(f"{tag}: {value}" for tag, value in row["exif_tags"])
